### ISSUE TITLE
sample_dataset  module not found

### ISSUE THREAD

**Issue by nickums** [huggingface/setfit#274] opened 2023-01-17 10:11 UTC
working with the end-to-end example in the README:
    from setfit import SetFitModel, SetFitTrainer, sample_dataset
sample-dataset is not found

Another problem:
    from datasets import load_dataset  
module is not found.  I had to do this:
    from datasets.load import load_dataset

**Comment by tomaarsen** [comment] 2023-01-17 21:18
Perhaps your `setfit` and `datasets` versions are out of date, because I am unable to reproduce this:
```python
>>> from setfit import SetFitModel, SetFitTrainer, sample_dataset
>>> sample_dataset
<function sample_dataset at 0x000002223627BE20>
>>> from datasets import load_dataset
>>> load_dataset
<function load_dataset at 0x000002223627B7F0>
```

Alternatively, you may have a folder or file called `setfit`, `setfit.py`, `datasets` or `datasets.py`, in which case they might cause the issues.

I'll close this, as I don't think it's an issue on the newer versions, but feel free to reply if you have any questions or need help.

- Tom Aarsen

**Closed by tomaarsen** 2023-01-17 21:18 UTC

**Comment by nickums** [comment] 2023-01-19 13:11
thanks very much for your response, upgrading datasets to  2.8.0 and setfit to 0.5.0 works

**Comment by tomaarsen** [comment] 2023-01-19 13:37
I'm glad to hear it!
