### ISSUE TITLE
Set good default value for `n_jobs` of Scikit-Learn  classification heads

### ISSUE THREAD

**Issue by lewtun** [huggingface/setfit#165] opened 2022-11-09 12:39 UTC
Currently we use the default value of `n_jobs` when instantiating the Scikit-Learn classification head (see e.g. [here](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html?highlight=logistic) for details).

We should increase this from 1 to a sensible default (maybe `n_jobs=-1` is OK for most cases?). It could potentially be an argument that's also passed to the `SetFitTrainer`

**Comment by LordReigns** [comment] 2022-11-10 15:09
Hello @lewtun,

First time contributor here, I would like to work on this issue if it is not assigned to anyone yet. 😄

**Comment by tomaarsen** [comment] 2022-11-10 15:09
The default of `n_jobs=-1` seems sensible for [`LogisticRegression`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html). That said, I don't see why this ought to be added to the `SetFitTrainer` necessarily, as it is already easy to instantiate the logistic regression head with any `n_jobs`:
```python
>>> from setfit import SetFitModel
>>> head_params = {
...     "n_jobs": 1,
... }
>>> model = SetFitModel.from_pretrained(
...     "sentence-transformers/paraphrase-albert-small-v2", head_params=head_params
... )
>>> model.model_head
LogisticRegression(n_jobs=3)
>>> trainer = SetFitTrainer(
...     model=model,
# Proceed like normal
```
Although I do recognize that it is nice to group all of the parameters that influence training speed into the Trainer.

I'd like to work on this, by the way.

**Comment by tomaarsen** [comment] 2022-11-10 17:06
I've done some further testing on this now to study the performance impacts of various values for `n_jobs`. In particular, I've applied the following hack to profile the time-performance of [`LogisticRegression.fit`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression.fit):
```python
import cProfile

def profiler(func):
    def wrapper(*args, **kwargs):
        datafn = f"{func.__name__}_n_jobs={args[0].n_jobs}.profile"
        prof = cProfile.Profile()
        retval = prof.runcall(func, *args, **kwargs)
        prof.dump_stats(datafn)
        return retval

    return wrapper

LogisticRegression.fit = profiler(LogisticRegression.fit)
```

I've combined this with a slightly modified variant of the first `README.md` example. To be specific, I've only added `head_params` to `SetFitModel.from_pretrained`, testing for various `n_jobs` values.
```python
from datasets import load_dataset
from sentence_transformers.losses import CosineSimilarityLoss
from sklearn.linear_model import LogisticRegression

from setfit import SetFitModel, SetFitTrainer, sample_dataset

# Load a dataset from the Hugging Face Hub
dataset = load_dataset("sst2")

# Simulate the few-shot regime by sampling 8 examples per class
train_dataset = sample_dataset(dataset["train"], label_column="label", num_samples=8)
eval_dataset = dataset["validation"]

potential_n_jobs = [1, 2, 4, -1]
for n_jobs in potential_n_jobs:
    # Load a SetFit model from Hub
    head_params = {
        "n_jobs": n_jobs,
    }
    model = SetFitModel.from_pretrained(
        "sentence-transformers/paraphrase-mpnet-base-v2",
        head_params=head_params
    )

    # Create trainer
    trainer = SetFitTrainer(
        model=model,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        loss_class=CosineSimilarityLoss,
        metric="accuracy",
        batch_size=16,
        num_iterations=20,  # The number of text pairs to generate for contrastive learning
        num_epochs=1,  # The number of epochs to use for constrastive learning
        column_mapping={"sentence": "text", "label": "label"}  # Map dataset columns to text/label expected by trainer
    )
    trainer.train()
```

This produces 4 files, which can easily be inspected using `snakeviz`:
| `n_jobs` | `Profiler screenshot` | `Total fitting time` |
| ------------- | ------------- | ---- |
| 1  | ![image](https://user-images.githubusercontent.com/37621491/201152836-60a7f7e8-d77a-4d68-b427-baac12ab0110.png) | 0.0126s |
| 2  | ![image](https://user-images.githubusercontent.com/37621491/201152896-4297abbe-9e82-445d-af4b-4949a3034103.png)  | 2.14s |
| 4  | ![image](https://user-images.githubusercontent.com/37621491/201152952-217703a4-8fdc-4b79-8d0c-f33879704be2.png) | 2.47s |
| -1  | ![image](https://user-images.githubusercontent.com/37621491/201152993-6f4de176-0507-4557-b193-98be13399fbb.png) | 3.24s |

I've performed these same experiments again, except for `num_samples=500` of the `sst2` dataset instead of `8`, and found similar results:
```
n_jobs=1  => 0.0720s
n_jobs=2  => 2.16s
n_jobs=4  => 2.37s
n_jobs=-1 => 3.19s
```
and once for `num_samples=5000`:
```
n_jobs=1  => 0.683s
n_jobs=2  => 2.85s
n_jobs=4  => 3.03s
n_jobs=-1 => 4.35s
```

Though far from scientific, from this we can draw a very simple conclusion: due to the low-data nature of SetFit, simply using 1 CPU core is more effective in these tests than waiting for `threading` to get a hold of all cores. For context, I'm using an i7-8750H, but these results should be comparable for other processors. 
I suspect that on my device, I would only see performance gains with increasing `n_jobs` when using 100k training samples or more, at which point you could argue that a few-shot approach is no longer the way to go.

As a result, I would advise keeping the `n_jobs` at the default like it is now. If users run into specific circumstances where they believe there is some performance gain to be made with a larger `n_jobs`, then they can always use the `head_params` option in `SetFitModel.from_pretrained`.

Another thing to mention - the fitting time of the logistic regression head is negligible to the finetuning time of the sentence transformer. In the grand scheme of things, the logistic regression head fitting time is not something to concern ourselves with.

---

Also, I now see that @LordReigns and I posted a message at the same time! If you want, then you can take this one, but I think some more discussion might be needed on whether this change is actually beneficial or required, as I believe the current situation is best. 
However, if you do turn this into a PR, I'll happily help review it.

- Tom Aarsen

**Closed** 2022-11-11 16:48 UTC
Labels: enhancement, good first issue
